// This code conforms with the UFC specification version 2016.1.0
// and was automatically generated by FFC version 2016.1.0.
// 
// This code was generated with the following parameters:
// 
//   convert_exceptions_to_warnings: False
//   cpp_optimize:                   True
//   cpp_optimize_flags:             '-O3 -ffast-math -march=native'
//   epsilon:                        1e-14
//   error_control:                  False
//   form_postfix:                   False
//   format:                         'ufc'
//   no-evaluate_basis_derivatives:  True
//   optimize:                       False
//   precision:                      15
//   quadrature_degree:              -1
//   quadrature_rule:                'auto'
//   representation:                 'auto'
//   split:                          False

#ifndef __FFC_FORM_C124D71786B4C04874DCF763D649C8EEDE34A4AA_H
#define __FFC_FORM_C124D71786B4C04874DCF763D649C8EEDE34A4AA_H
#include <stdexcept>
#include <ufc.h>

extern "C" ufc::finite_element * create_ffc_form_c124d71786b4c04874dcf763d649c8eede34a4aa_finite_element_0();


extern "C" ufc::finite_element * create_ffc_form_c124d71786b4c04874dcf763d649c8eede34a4aa_finite_element_1();


extern "C" ufc::finite_element * create_ffc_form_c124d71786b4c04874dcf763d649c8eede34a4aa_finite_element_2();


extern "C" ufc::finite_element * create_ffc_form_c124d71786b4c04874dcf763d649c8eede34a4aa_finite_element_3();


extern "C" ufc::finite_element * create_ffc_form_c124d71786b4c04874dcf763d649c8eede34a4aa_finite_element_4();


extern "C" ufc::finite_element * create_ffc_form_c124d71786b4c04874dcf763d649c8eede34a4aa_finite_element_5();


extern "C" ufc::finite_element * create_ffc_form_c124d71786b4c04874dcf763d649c8eede34a4aa_finite_element_6();


extern "C" ufc::dofmap * create_ffc_form_c124d71786b4c04874dcf763d649c8eede34a4aa_dofmap_0();


extern "C" ufc::dofmap * create_ffc_form_c124d71786b4c04874dcf763d649c8eede34a4aa_dofmap_1();


extern "C" ufc::dofmap * create_ffc_form_c124d71786b4c04874dcf763d649c8eede34a4aa_dofmap_2();


extern "C" ufc::dofmap * create_ffc_form_c124d71786b4c04874dcf763d649c8eede34a4aa_dofmap_3();


extern "C" ufc::dofmap * create_ffc_form_c124d71786b4c04874dcf763d649c8eede34a4aa_dofmap_4();


extern "C" ufc::dofmap * create_ffc_form_c124d71786b4c04874dcf763d649c8eede34a4aa_dofmap_5();


extern "C" ufc::dofmap * create_ffc_form_c124d71786b4c04874dcf763d649c8eede34a4aa_dofmap_6();




extern "C" ufc::form * create_ffc_form_c124d71786b4c04874dcf763d649c8eede34a4aa_form_0();

#endif
